### ISSUE TITLE
Image fetch failed

### ISSUE THREAD

**Issue by lszddz** [omnivore-app/obsidian-omnivore#106]
Hello, thank you for your hard work. 
I encountered a problem when using this plugin, that is, the image does not display properly in obsidian, the image link seems broken. For example: https:&#x2F; &#x2F; proxy-prod.omnivore-image-cache.app&#x2F; 827x604,se2o9eqlBBtHPXRgF3jm7YpvSVhRuxbhQDDtwP4JHAVs&#x2F; https:&#x2F; &#x2F; www.logseqtimes.com&#x2F; content&#x2F; images&#x2F; 2023&#x2F; 07&#x2F; image-13.png.
This is not even a full link. I can not open the link in the browser, too.

**Comment by ParkJaeSeong** [comment]
same problem. +1
here is my case.

- original image link https://miro.medium.com/v2/resize:fit:1400/format:webp/1*GbshlGqHAi8agfGLEi-Y2g.jpeg

- omnivore markdown
![](https:&#x2F;&#x2F;proxy-prod.omnivore-image-cache.app&#x2F;700x386,sEXXaldFHKmqENZ115Rvv1t7Ss19TX1LckXMQGdlZBKM&#x2F;https:&#x2F;&#x2F;miro.medium.com&#x2F;v2&#x2F;resize:fit:1400&#x2F;1*GbshlGqHAi8agfGLEi-Y2g.jpeg)

markdown, i think
![](https://proxy-prod.omnivore-image-cache.app/700x386,sEXXaldFHKmqENZ115Rvv1t7Ss19TX1LckXMQGdlZBKM/https://miro.medium.com/v2/resize:fit:1400/1*GbshlGqHAi8agfGLEi-Y2g.jpeg)

I don't know why '/' changed to '&#x2F;'.

**Comment by sywhb** [comment]
Hey @lszddz @ParkJaeSeong, sorry for the late reply.

I wonder if you guys are using `{{ content }}` in the template because for mustache template, using double brackets surrounding the variables means characters will be escaped in HTML so the `/` becomes `&#x2F;`.

Using triple brackets like `{{{ content }}}` will unescape HTML and I suggest using it for the variables in the template
