### ISSUE TITLE
Clipping a page with omnivore resulted in obsidian black screen on desktop and android app crashing

### ISSUE THREAD

**Issue by c1505** [omnivore-app/obsidian-omnivore#163]
Obsidian should not crash based on the content in markdown file and I opened a bug for that side of things. https://forum.obsidian.md/t/obsidian-screen-goes-black-seconds-after-opening/71926/2 . I think this problem could also be prevented by the plugin.

# Setup
- page content enabled in sync
- windows 11

# What happened
- Clipped this page with omnivore https://github.com/openai/evals/tree/main/evals/registry/evals
- When omnivore synced, obsidian desktop turned to a black screen. Restarting, It would turn into a black screen in less than 5 seconds. 
- Troubleshooting other aspects did not fix obsidian
- The resulting markdown file created was 12 MB. I think largely because it has the last commit message for every file on that page and each of these commit messages is large
- deleting this file, fixed the problem

# Possible changes that could prevent this problem from happening
- An omnivore plugin setting that allows for a limitation of file size for import
- Omnivore removes/sanitizes file content that would cause obsidian to crash

# Additional details
- I am not sure if it is the length size of the file or the file content that caused problems
- The clipped file also would not render in vscode's markdown preview

**Comment by sywhb** [comment]
Hey @c1505 , thanks for the detailed report!

Yeah I think if the file is too big, Obsidian will likely crush. Actually we do have a file size limit which is around 12MB but I guess it's still too big for Obsidian since it has to load it into memory.

I think to have a size limitation settings makes a lot of sense so we could reduce the file size and show some warnings.
