### ISSUE TITLE
add a Option to turn off the new feature：start to sync when plugin is loaded

### ISSUE THREAD

**Issue by calmwaves111** [omnivore-app/obsidian-omnivore#174]
I hope I can have complete control over the sync
In fact, I don't want it to run when starting obsidian because it would slow down my startup speed

**Comment by mem89de** [comment]
I support this request.

Frequency is set to `0` in my settings, this is explicitly labelled as manual sync. Why would I want it to sync at startup?

**Comment by blakeNaccarato** [comment]
I do like that auto-sync on startup is possible, but agree that it should be configurable, and that sync toasts should be disabled for any auto-sync behaviors.

Toasting button-click/manual sync makes sense, because a user expects the app to react to their intent. Toasting auto-sync (including periodic auto-sync) may tend to surprise the user, so I don't think that toasts should appear then.

I open Obsidian many times a day to jot things down, and usually it's starting up from scratch, so now I see two Omnisearch toasts obscuring UI every time I open the app. You've gotta tap away the toasts just to see the note header and options, for instance.

I do think that it's reasonable to default to auto-sync on startup on new installs, so new users aren't surprised by out-of-sync vaults, as long as its configurable.

**Comment by caunus** [comment]
Agreed, suddenly everything is sync. That's not user firendly. Default should be "No sync on startup"!
Currently it's a bug not a feature!

**Comment by DistroByte** [comment]
+1 to this feature request! When using git as source control it prevents pulls from completing successfully because of the conflicting files (local unstaged change to timestamp and upstream "old" timestamp).

Obviously the change can be discarded, but its an extra hurdle to cross.

**Comment by merqrial** [comment]
+1 to be able to disable this. It updates the last sync timestamp at every obsidian restart. That creates conflicts in git sync. Please can we go ahead with a hacky approach for now? This feature needs to be stopped and enabled with the option to disable it later.

**Comment by sywhb** [comment]
hey guys, i just added this option in v1.9.4

<img width="781" alt="Screenshot 2024-02-20 at 11 19 35 AM" src="https://github.com/omnivore-app/obsidian-omnivore/assets/12963965/ea8767da-f70b-4c32-8138-89f069aece4e">

please let me know if it suits your need

**Comment by DistroByte** [comment]
Perhaps renaming the heading to "Sync on startup" might be clearer, like how obsidian git has named it? 

![image](https://github.com/omnivore-app/obsidian-omnivore/assets/58866873/dd4ca6c9-1357-40df-b2d9-47457c97038d)

**Comment by sywhb** [comment]
> Perhaps renaming the heading to "Sync on startup" might be clearer, like how obsidian git has named it? "start" might not be descriptive enough for people
> 
> ![image](https://private-user-images.githubusercontent.com/58866873/306125604-dd4ca6c9-1357-40df-b2d9-47457c97038d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDA0MDQsIm5iZiI6MTcwODQwMDEwNCwicGF0aCI6Ii81ODg2Njg3My8zMDYxMjU2MDQtZGQ0Y2E2YzktMTM1Ny00MGRmLWIyZDktNDc0NTdjOTcwMzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAzMzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NWU1ZDg1Y2M0ZTYzNWFkNzc4ZDczMzU5OTg2YjlhODFlODk3Yjk3ZTVkYTEzZmRiNmU2YmRlYTRiZDkxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMDReHp9JtL47jGI0uLfUJkwowzYSlSJFx7ssanaDAI)

yeah, it is clearer to use startup 👍  i will rename it in the next release. thank you!
